/* eslint-disable max-len */
import moment from 'moment';
import { CollageOutput, ProjectConfig } from '../interfaces';
import { MEOWSDAO_GNOSIS_SAFE } from './index';
import { random } from '../utils';
import {
  collage11110,
  collage4444,
  collage4000,
  collage5000,
  collageDiscord600x240,
  collageTwitter1200x675,
  collageTwitter1500x500,
  collage10000,
} from './collages';
import { bannyConfig } from './project-banny';

const iso_datetime_now = new Date().toISOString();

export const folder_names = {
  output: 'build',
  layered_assets: 'layered-assets',
  traits: 'Traits',
};

const glo_gang_description: string =
  `GloGang Creative Director ColourfulMula and Multi-Platinum recording artist Chief Keef, ` +
  `CEO of GloGang Worldwide present 4,444 generative art NFTs of their GloMan character ` +
  `released by OneOf, Incorporated. 4,444 is symbolic to the Glo’s as it represents self-mastery ` +
  `and determination. 4444 is the number of the master builder. Many assume that society would not ` +
  `exist if not for the power of the sun- our true master builder. Seeing 4444 is a sign that all ` +
  `your hard work is soon going to be rewarded, for you have achieved self-mastery.`;

const glo_baby_description = `
It's been just two months since the Glo's joined forces with human allies. The Glo's are thriving, emanating more light and healing power than ever before. Supreme Leader Kim Jong-Un is in retreat—but for how long? A leak from RGB sources disclose a secret serum being formulated—a kryptonite that could wipe out the entire GloGang race! Powered by DNA from our very own Glo Sister, the RGB declares the Glo's extinction is all but guaranteed.
Thankfully, the Glo's have been strong and prosperous, and in a matter of days a new generation of GloBabies will be born! But… just like the Glo's, the GloBabies need human allies to survive. Some will be delivered. Some will be fostered. All will be trained for GloGang mastery—and to generate light and bring our long lost Glo Sister home, once and for all.
  `;
const whiskers_description =
  "Meows(DAO)'s Genesis NFT collection are hand-drawn illustrations by artist Natasha Pankina (@natashapankina5) with a little help from Layer-cake (@atsignhandle and @gibbinator). This NFT collection expands the universe of Mr.Whiskers (Inventor of Proof of Meow\u2122 and CEO of CompuGlobalHyperMega (DAO)) by introducing his Progeny.";
const test_description =
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

const meow_colors = [
  'F6A3AD',
  'FF808D',
  'FFAFB9',
  'CBEEC2',
  '8EE9F2',
  'F5F3BA',
  '71CEF3',
  'FCEEB2',
  'FCAD5E',
  'FB6155',
  'E5BBD7',
  'AFD7D0',
];

const meowConfig: ProjectConfig = {
  name: `meowsdao`,
  resume_folder: '',
  re_generate_collages: false,
  upload_images_to_ipfs: false,
  upload_metadata_to_ipfs: false,
  //stunt_populations_to: 15,
  hide_rarity_names: true,
  rotated_images_allowed: 2000,
  shuffle_assets: true,
  metadata_input: {
    name: `Whiskers' Progeny`,
    symbol: 'MEOW',
    description: whiskers_description,
    birthdate: `${moment(iso_datetime_now)
      .subtract(365 + random(365 * 2), 'days')
      .toISOString()}`,
    background_colors: meow_colors,
    minter: `0x971B4533EdBFcfE34e0F6eA053D33231a814FD96`,
    creators: [`Natasha Pankina, n@meowsdao.xyz`],
    publishers: [`@atsignhandle`],
    genres: [`meow`, `character`, `profile`],
    tags: [`XTZ`],
    drop_date: `${iso_datetime_now}`,
    native_size: '2084x2084',
    more_info_link: 'https://meowsdao.xyz',
    include_total_population_in_name: true,
    royalties: {
      artist_address: `0xB772C38aCa8fac0FB50Fd01899ef3Dfa8B7DF628`,
      artist_percentage: 10,
      additional_payee: '0x971B4533EdBFcfE34e0F6eA053D33231a814FD96',
      additional_payee_percentage: 5,
    },
    decimals: 0,
    generation: 0,
    edition: 0,
  },
  metadata_outputs: ['ethereum', 'tezos'],
  metadata_file_extension: false,
  image_outputs: [
    { width: 350, height: 350, tag: 'icon', ipfs_tag: 's' }, // feeds into collage, please don't remove.
    { width: 512, height: 512, tag: 'profile', ipfs_tag: '' },
    { width: 1_500, height: 1_500, tag: 'image', ipfs_tag: '' },
  ],
  anim_outputs: [],
  collage_outputs: [
    collage10000,
    collage4000,
    collage5000,
    collageTwitter1200x675,
    collageTwitter1500x500,
    collageDiscord600x240,
  ],
  stacked_gif_outputs: [
    {
      tag: 'stacked-gif',
      source_image_type: 'profile',
      max_stacks: 100,
      images_per_stack: 100,
    },
  ],
  populations: [
    {
      name: 'diamond-hands',
      layer_order: [
        'Backgrounds',
        'Fur',
        'Ears',
        'Brows',
        'Eyes',
        'Nose',
        'Shirt',
        'Tie',
        'Blazer',
        'Headwear',
        'Glasses',
        'Signature',
      ],
      population_size: 1,
    },
    {
      name: 'pentaptych-alps',
      layer_order: [
        'Background',
        'Fur',
        'Ears',
        'Brows',
        'Eyes',
        'Nose',
        'Henley',
        'Headwear',
        'Glasses',
        'Collar',
        'Signature',
      ],
      population_size: 5,
    },
    {
      name: 'pentaptych-space',
      layer_order: [
        'Background',
        'Fur',
        'Ears',
        'Brows',
        'Eyes',
        'Nose',
        'Henley',
        'Headwear',
        'Glasses',
        'Collar',
        'Signature',
      ],
      population_size: 5,
    },
    {
      name: 'pentaptych-underwater',
      layer_order: [
        'Background',
        'Fur',
        'Ears',
        'Brows',
        'Eyes',
        'Nose',
        'T-shirt',
        'Pattern',
        'Headwear',
        'Glasses',
        'Signature',
      ],
      population_size: 5,
    },
    {
      name: 'naked',
      layer_order: [
        'Background',
        'Fur',
        'Ears',
        'Brows',
        'Eyes',
        'Nose',
        'Nipples',
        'Headwear',
        'Glasses',
        'Collar',
        'Signature',
      ],
      population_size: 5996,
    },
    {
      name: 't-shirt',
      layer_order: [
        'Background',
        'Fur',
        'Ears',
        'Brows',
        'Eyes',
        'Nose',
        'T-shirt',
        'Pattern',
        'Headwear',
        'Glasses',
        'Signature',
      ],
      population_size: 3996,
    },
    {
      name: 'henley',
      layer_order: [
        'Background',
        'Fur',
        'Ears',
        'Brows',
        'Eyes',
        'Nose',
        'Henley',
        'Headwear',
        'Glasses',
        'Collar',
        'Signature',
      ],
      population_size: 5996,
    },
    {
      name: 'shirt',
      layer_order: [
        'Background',
        'Fur',
        'Ears',
        'Brows',
        'Eyes',
        'Nose',
        'Shirt',
        'Tie',
        'Blazer',
        'Headwear',
        'Glasses',
        'Signature',
      ],
      population_size: 3995,
    },
  ],
  re_generate_metadata_cid: false,
  excluded_layers_from_metadata: [],
};

const gloConfig: ProjectConfig = {
  name: 'glo-gang',
  //stunt_populations_to: 10,
  upload_images_to_ipfs: true,
  upload_metadata_to_ipfs: false,
  re_generate_collages: false,
  resume_folder: '',
  metadata_outputs: ['tezos'],
  metadata_file_extension: false,
  rotated_images_allowed: 0,
  shuffle_assets: false,
  metadata_input: {
    name: 'GloGang',
    symbol: 'GLO',
    description: glo_gang_description,
    minter: 'tz1i8D4DHkuQsGgpxEaHPRsdYtKCFMnmeN6Z',
    creators: ['Chief Keef X ColourfulMula', 'GloGang Worldwide, Inc'],
    publishers: ['OneOf, Inc.'],
    genres: [`GloGang`, `character`, `profile`],
    tags: [`XTZ`],
    drop_date: `${iso_datetime_now}`,
    native_size: '3301x3301',
    more_info_link: 'https://www.oneof.com/GloGang',
    include_total_population_in_name: false,
    royalties: {
      decimals: 2,
      shares: {
        tz2CG8EvFSCsghhTVchANGd35MdXx5KRA3cV: 10,
      },
    },
    rights: `© 2021 GloGang Worldwide and OneOf, Inc. All rights reserved.`,
    decimals: 0,
    generation: 0,
    edition: 0,
  },
  image_outputs: [
    { width: 350, height: 350, tag: 'icon', ipfs_tag: 's' },
    { width: 512, height: 512, tag: 'profile', ipfs_tag: '' },
    { width: 3000, height: 3000, tag: 'image', ipfs_tag: 'l' },
  ],
  anim_outputs: [
    // { width: 500, height: 500, tag: 'rain', background_animation: 'rain' },
  ],
  stacked_gif_outputs: [
    {
      tag: 'stacked-gif',
      source_image_type: 'profile',
      max_stacks: 100,
      images_per_stack: 100,
    },
  ],
  populations: [
    {
      name: 'legend-1',
      population_size: 1,
      layer_order: [
        'Backgrounds',
        'Body',
        'Shirt',
        'Clothes',
        'Face',
        'Eyes',
        'Browz',
        'Mouth',
        'Hats&Hair',
        'FaceWear',
      ],
    },
    {
      name: 'legend-2',
      population_size: 1,
      layer_order: [
        'Backgrounds',
        'Body',
        'Shirt',
        'Clothes',
        'Face',
        'Eyes',
        'Browz',
        'Mouth',
        'Hats&Hair',
        'FaceWear',
      ],
    },
    {
      name: 'legend-3',
      population_size: 1,
      layer_order: ['Backgrounds', 'Body', 'Shirt', 'Jersey', 'Face', 'Eyes', 'Browz', 'Mouth'],
    },
    {
      name: 'legend-4',
      population_size: 1,
      layer_order: [
        'Backgrounds',
        'Body',
        'Shirt',
        'Jersey',
        'Face',
        'Eyes',
        'Browz',
        'Mouth',
        'FaceWear',
        'Hats&Hair',
      ],
    },

    {
      name: 'glo-gang',
      population_size: 4440,
      layer_order: [
        'Backgrounds',
        'Body',
        'Shirt',
        'Clothes',
        'Jersey',
        'Face',
        'Eyes',
        'Browz',
        'Mouth',
        'FaceWear',
        'Hats&Hair',
      ],
    },
  ],
  collage_outputs: [collage4444, collageTwitter1200x675, collageTwitter1500x500],
  re_generate_metadata_cid: false,
  excluded_layers_from_metadata: [],
};

const globabyConfig: ProjectConfig = {
  name: 'glo-baby',
  //stunt_populations_to: 10,
  upload_images_to_ipfs: true,
  upload_metadata_to_ipfs: true,
  re_generate_collages: false,
  resume_folder: '20220118-18215829',
  metadata_outputs: ['tezos'],
  metadata_file_extension: true,
  rotated_images_allowed: 0,
  shuffle_assets: false,
  metadata_input: {
    name: 'GloBaby',
    symbol: 'GLOB',
    description: glo_baby_description,
    minter: 'tz1i8D4DHkuQsGgpxEaHPRsdYtKCFMnmeN6Z',
    creators: ['Chief Keef X ColourfulMula', 'GloGang Worldwide, Inc'],
    publishers: ['OneOf, Inc.'],
    genres: [`GloGang`, `character`, `profile`],
    tags: [`XTZ`],
    drop_date: `${iso_datetime_now}`,
    native_size: '5716x5716',
    more_info_link: 'https://www.oneof.com/GloBaby',
    include_total_population_in_name: false,
    royalties: {
      decimals: 2,
      shares: {
        tz2CG8EvFSCsghhTVchANGd35MdXx5KRA3cV: 10,
      },
    },
    rights: `© 2021 GloGang Worldwide and OneOf, Inc. All rights reserved.`,
    decimals: 0,
    generation: 0,
    edition: 0,
  },
  image_outputs: [
    { width: 350, height: 350, tag: 'icon', ipfs_tag: 's' },
    { width: 512, height: 512, tag: 'profile', ipfs_tag: '' },
    { width: 3000, height: 3000, tag: 'image', ipfs_tag: 'l' },
  ],
  anim_outputs: [
    // { width: 500, height: 500, tag: 'rain', background_animation: 'rain' },
  ],
  stacked_gif_outputs: [
    {
      tag: 'stacked-gif',
      source_image_type: 'profile',
      max_stacks: 100,
      images_per_stack: 100,
    },
  ],
  populations: [
    {
      name: 'legend-1',
      population_size: 1,
      layer_order: [
        'GloBabyBackground',
        'GloBabyBody',
        'GloBabyDiaper',
        'GloBabyPin',
        'GloBabyOutline',
        'GloBabyClothing',
        'GloBabyBib',
        'GloBabyMouth',
        'GloBabyEyes',
        'GloBabyToys',
      ],
    },
    {
      name: 'legend-2',
      population_size: 1,
      layer_order: [
        'GloBabyBackground',
        'GloBabyBody',
        'GloBabyDiaper',
        'GloBabyPin',
        'GloBabyOutline',
        'GloBabyClothing',
        'GloBabyBib',
        'GloBabyMouth',
        'GloBabyEyes',
        'GloBabyToys',
      ],
    },
    {
      name: 'legend-3',
      population_size: 1,
      layer_order: [
        'GloBabyBackground',
        'GloBabyBody',
        'GloBabyDiaper',
        'GloBabyPin',
        'GloBabyOutline',
        'GloBabyClothing',
        'GloBabyBib',
        'GloBabyMouth',
        'GloBabyEyes',
        'GloBabyToys',
      ],
    },
    {
      name: 'legend-4',
      population_size: 1,
      layer_order: [
        'GloBabyBackground',
        'GloBabyBody',
        'GloBabyDiaper',
        'GloBabyPin',
        'GloBabyOutline',
        'GloBabyClothing',
        'GloBabyBib',
        'GloBabyMouth',
        'GloBabyEyes',
        'GloBabyToys',
      ],
    },
    {
      name: 'glo-baby',
      population_size: 2218,
      layer_order: [
        'GloBabyBackground',
        'GloBabyBody',
        'GloBabyDiaper',
        'GloBabyPin',
        'GloBabyOutline',
        'GloBabyClothing',
        'GloBabyBib',
        'GloBabyMouth',
        'GloBabyEyes',
        'GloBabyToys',
      ],
    },
  ],
  collage_outputs: [collage4444, collageTwitter1200x675, collageTwitter1500x500],
  re_generate_metadata_cid: true,
  excluded_layers_from_metadata: ['GloBabyOutline'],
};

const testConfig: ProjectConfig = {
  name: `test`,
  resume_folder: '',
  re_generate_collages: false,
  upload_images_to_ipfs: false,
  upload_metadata_to_ipfs: false,
  rotated_images_allowed: 10,
  shuffle_assets: true,
  metadata_input: {
    name: 'Test',
    symbol: 'TEST',
    description: test_description,
    minter: '0x971B4533EdBFcfE34e0F6eA053D33231a814FD96',
    creators: [`the Lord`, `the Sun`, `the Holy G`],
    publishers: [`Publisher A`],
    genres: [`character`, `profile`, `hand-drawn-art`],
    tags: [`ETH`],
    drop_date: `${iso_datetime_now}`,
    native_size: '3301x3301',
    more_info_link: '',
    include_total_population_in_name: true,
    decimals: 0,
    generation: 0,
    edition: 0,
  },
  metadata_outputs: ['tezos', 'ethereum'],
  metadata_file_extension: true,
  image_outputs: [
    { width: 350, height: 350, tag: 'icon', ipfs_tag: 's' }, // feeds into collage, please don't remove.
    { width: 1_500, height: 1_500, tag: 'image', ipfs_tag: '' },
  ],
  anim_outputs: [],
  stacked_gif_outputs: [],
  collage_outputs: [collage4000],
  populations: [
    {
      name: 'test-population',
      layer_order: ['Background', 'Circle', 'Square', 'Triangle'],
      population_size: 30,
    },
  ],
  re_generate_metadata_cid: false,
  excluded_layers_from_metadata: [],
};

export const project_config: ProjectConfig[] = [meowConfig, gloConfig, testConfig, globabyConfig, bannyConfig];
